### ISSUE TITLE
model模板中的tableName自带单引号导致无法正常执行gorm.AutoMigrate

### ISSUE THREAD

**Issue by priceou** [SpectatorNan/gorm-zero#12]
数据库为mysql
通过模板生成的***_gen.go文件
其中的指定gorm的表名的方法
`
func (SysConfig) TableName() string {
	return "`sys_config`"
}
`

表名会自带单引号
这会导致执行gorm的迁移方法时报错
`
err := conn.AutoMigrate(&SysConfig{})
`

在gorm的迁移方法中判断表是否存在会根据表名去搜索information_schema.tables
但此时带入的参数是'`sys_config`'而不是 ‘sys_config’导致查询出错
最终会报 create table 'sys_config' exists

**Comment by SpectatorNan** [comment]
n

> 数据库为mysql 通过模板生成的***_gen.go文件 其中的指定gorm的表名的方法 ` func (SysConfig) TableName() string { return "`sys_config`" } `
> 
> 表名会自带单引号 这会导致执行gorm的迁移方法时报错 `err := conn.AutoMigrate(&SysConfig{})`
> 
> 在gorm的迁移方法中判断表是否存在会根据表名去搜索information_schema.tables 但此时带入的参数是'`sys_config`'而不是 ‘sys_config’导致查询出错 最终会报 create table 'sys_config' exists

你可以修改一下模版文件
将
model/model-new.tpl 中
```
func ({{.upperStartCamelObject}}) TableName() string {
    return {{.table}}
}
```
这一块去掉
然后gorm会自动通过struct name 映射表名
```
