### ISSUE TITLE
gorm 事务要如何使用比较优良？

### ISSUE THREAD

**Issue by crazy6995** [SpectatorNan/gorm-zero#4]
弱弱的提几个问题。。。

1. model层是否应该向外暴露 gorm.DB？
2. 事务应该如何实现？

对于`1`，个人想法是不应该将 gorm.DB 暴露到 `model` 之外。

对于`2`，个人的实现方式是新增接口 `Transact(fn func(tx *gorm.DB) error)`，这个`fn`中是否应该直接使用`tx`执行操作呢？如果使用`tx`直接操作数据库，会出现过度耦合（即`logic`直接使用 tx，而不是使用model暴露的接口）

目前个人的实现方式是将所有的 Insert / Update / Delete 等接口均添加 `tx *gorm.DB`，上面所述的 `tx` 不直接操作数据库，而是再次调用 model 中的接口，将其传递过去使用。

```golang
// 注1：UserModel未开启cache
// 伪代码如下
l.svcCtx.UserModel.TransactCtx(l.ctx, nil, func(tx *gorm.DB) error {
    if err := l.svcCtx.UserModel.Update(l.ctx, tx, &User{}); err != nil {
      if errors.Is(err, model.ErrRowsAffectedZero) {
        l.svcCtx.UserModel.Insert(l.ctx, tx, &User{})
      }
    }
})
// 接口定义
// TransactCtx(ctx context.Context, tx *gorm.DB, fn func(tx *gorm.DB) error, opts ...*sql.TxOptions) error

// 1. 开启事务
// 2. 使用事务`gorm.DB`执行`UserModel`暴露的`Update`方法
// 3. 未能正常更新（记录不存在），使用事务`gorm.DB`执行`UserModel`暴露的`Insert`方法
```

这种场景在未开启`Cache`时候使用正常，但如果开启了`Cache`，则可能需要修改`cachedgorm.go`，允许 `tx *gorm.DB` 传递进去进行使用？

目前还没有比较好的办法，并且对于我这种使用事务的方式可能不是很靠谱，想问一下有没有更好的办法？

**Comment by crazy6995** [comment]
也许将

```golang
l.svcCtx.UserModel.TransactCtx(l.ctx, nil, func(tx *gorm.DB) error {
    if err := l.svcCtx.UserModel.Update(l.ctx, tx, &User{}); err != nil {
      if errors.Is(err, model.ErrRowsAffectedZero) {
        l.svcCtx.UserModel.Insert(l.ctx, tx, &User{})
      }
    }
})
```

放到 model 里会更好吧。

**Comment by SpectatorNan** [comment]
cachedgorm 中含事务方法
![image](https://user-images.githubusercontent.com/13959374/168570889-504fd050-d6c6-4ddc-9afb-4a47f5cbcaca.png)

跨model 事务 可以参考 go zero looklook 。事务依赖于事务 gorm.DB， 所以需要传递
![image](https://user-images.githubusercontent.com/13959374/168571105-80f640f0-cec4-41ea-818f-5384715f9637.png)

这个是我目前写的一个事务实现
![image](https://user-images.githubusercontent.com/13959374/168571308-abde51d0-4ce9-459b-b161-5bb4c165a002.png)

**Comment by SpectatorNan** [comment]
link https://github.com/Mikaelemmmm/go-zero-looklook/blob/main/app/payment/model/thirdPaymentModel.go

**Comment by SpectatorNan** [comment]
> 这种场景在未开启Cache时候使用正常，但如果开启了Cache，则可能需要修改cachedgorm.go，允许 tx *gorm.DB 传递进去进行使用？

或许需要添加一个暴露手动事务的方法用以获取事务DB

**Comment by crazy6995** [comment]
我目前也是这么用的

直接修改了模板，并且仿造 sql.sqlconn 添加了一个 gormconn

未开启cache时，使用gormconn，开启时使用cachedgorm

所有的模板方法均添加了一个参数  gormconn/cachedgorm，同时添加一个工具用于获取真实使用的db实例 (WithTx)

**Comment by panhow** [comment]
刚开始使用这个模版，看到model的crud都有一个 tx 的声明看起来怪怪的


我以往的写法会在 svcCtx 中暴露一个，gorm.DB，用来在 logic 层里 暴露 conn.Transaction()，再通过这个 `tx *gorm.DB` 来创建 model，这样子如何？

@SpectatorNan 这是我的局部代码，请问这个办法如何？

```go

// svcCtx
type ServiceContext struct {
	Config config.Config

	DB        *gorm.DB
}


// logic code
ctx := context.Background()
l.svcCtx.DB.Transaction(func(tx *gorm.DB) error {
	var (
		domains []app.Domain
		routes  []app.Route
	)
	err = app.NewDomainModel(tx).BatchInsert(ctx, nil, domains)
	if err != nil {
		return err
	}
	err = app.NewRouteModel(tx).BatchInsert(ctx, nil, routes)
	if err != nil {
		return err
	}
})

```

**Comment by SpectatorNan** [comment]
以上评论是最初的模板  
这是现在更新的写法
参考于 [go-zero-looklook](https://github.com/Mikaelemmmm/go-zero-looklook/tree/main)
模版内部会根据是否传入tx决定是否执行于事务

```golang
// service context 
type ServiceContext struct {
	Config             config.Config 
	DBTransaction      func(fc func(tx *gorm.DB) error, opts ...*sql.TxOptions) error
	ConfigModel        productmodel.ConfigModel 
}
func NewServiceContext(c config.Config) *ServiceContext {
	db, _ := pg.ConnectWithConfig(c.Database, &gorm.Config{
		Logger: gormcCfg.NewDefaultGormLogger(&c.Database),
		//Logger: gormcCfg.NewDefaultZeroLogger(&c.Database),
		NamingStrategy: schema.NamingStrategy{
			SingularTable: true,
		},
	})
	if db == nil {
		panic("connect database failed")
	}
	cacheRedisConf := c.RedisConf.ToG0CacheConf() 
	return &ServiceContext{
		Config:             c, 
		DBTransaction:      db.Transaction,
		ConfigModel:        productmodel.NewConfigModel(db, cacheRedisConf), 
	}
}
// execute
err = l.svcCtx.DBTransaction(func(tx *gorm.DB) error {
		if oldUsername != usernameCfg.Value {
			usernameCfg.LastUserId = userServer.UserId
			err = l.svcCtx.ConfigModel.Update(l.ctx, tx, usernameCfg)
			if err != nil {
				return err
			}
		}
		if oldApiKey != apiKeyCfg.Value {
			apiKeyCfg.LastUserId = userServer.UserId
			err = l.svcCtx.ConfigModel.Update(l.ctx, tx, apiKeyCfg)
			if err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
}
```

**Comment by SpectatorNan** [comment]
> 刚开始使用这个模版，看到model的crud都有一个 tx 的声明看起来怪怪的
> 
> 我以往的写法会在 svcCtx 中暴露一个，gorm.DB，用来在 logic 层里 暴露 conn.Transaction()，再通过这个 `tx *gorm.DB` 来创建 model，这样子如何？
> 
> @SpectatorNan 这是我的局部代码，请问这个办法如何？
> 
> ```go
> // svcCtx
> type ServiceContext struct {
> 	Config config.Config
> 
> 	DB        *gorm.DB
> }
> 
> 
> // logic code
> ctx := context.Background()
> l.svcCtx.DB.Transaction(func(tx *gorm.DB) error {
> 	var (
> 		domains []app.Domain
> 		routes  []app.Route
> 	)
> 	err = app.NewDomainModel(tx).BatchInsert(ctx, nil, domains)
> 	if err != nil {
> 		return err
> 	}
> 	err = app.NewRouteModel(tx).BatchInsert(ctx, nil, routes)
> 	if err != nil {
> 		return err
> 	}
> })
> ```

 app.NewDomainModel(tx) 在调用时(事务中) 新创建model类型会产生额外开销。在频繁的请求中会出现内存消耗过高现象

**Comment by nullcache** [comment]
> go-zero-looklook

每次新建一个DBTransaction是不是太麻烦了，还要重新ConnectWithConfig

**Comment by nullcache** [comment]
update.tpl里加上 
```go
func (m *custom{{.upperStartCamelObject}}Model) Trans(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.conn.WithContext(ctx).Transaction(fn)
}
```
在带缓存的情况下会出现问题吗？因为我没怎么做过带缓存的，而且上面的讨论都太老了

**Comment by noahlann** [comment]
> update.tpl里加上 
> ```go
> func (m *custom{{.upperStartCamelObject}}Model) Trans(ctx context.Context, fn func(db *gorm.DB) error) error {
> 	return m.conn.WithContext(ctx).Transaction(fn)
> }
> ```
> 在带缓存的情况下会出现问题吗？因为我没怎么做过带缓存的，而且上面的讨论都太老了 @noahlann 

目前已经不使用gozero 的 orm 了，切换用别的了

**Comment by SpectatorNan** [comment]
> update.tpl里加上
> 
> func (m *custom{{.upperStartCamelObject}}Model) Trans(ctx context.Context, fn func(db *gorm.DB) error) error {
> 	return m.conn.WithContext(ctx).Transaction(fn)
> }
> 在带缓存的情况下会出现问题吗？因为我没怎么做过带缓存的，而且上面的讨论都太老了 [@noahlann](https://github.com/noahlann)

可以直接在svc中初始化一个trans方法。 直接l.svcCtx调用事务

**Comment by SpectatorNan** [comment]
svc中需要初始化DB  直接 

![Image](https://github.com/user-attachments/assets/b042e2cc-1ca0-431c-ab7f-19269654542c)

db在svc中的初始化:

![Image](https://github.com/user-attachments/assets/37e5947e-6092-4b88-acfc-06cc1e52f764)
