### ISSUE TITLE
可以将go-zero的logx默认集成进gorm吗,方便做日志收集

### ISSUE THREAD

**Issue by klen-ygs** [SpectatorNan/gorm-zero#44]
效果就像下面一样,日志带着traceid和spanid
![Screenshot_20231212_161611](https://github.com/SpectatorNan/gorm-zero/assets/105289582/aaa67b6c-4d67-4de0-b854-857bcf2b3696)

**Comment by SpectatorNan** [comment]
log方案有计划做的。只是最近在忙其他的事情没有时间弄去

**Comment by klen-ygs** [comment]
我自己做了一个简单的实现
https://github.com/klen-ygs/gorm-zero/commit/8b369de919d067d5bcebb7fbaf12bfda4625ab01
