### ISSUE TITLE
引用 database/sql 问题解决方案

### ISSUE THREAD

**Issue by klen-ygs** [SpectatorNan/gorm-zero#45]
gorm框架支持 sql.Named() 命名参数,所以在FindOne的模板上可以这样使用,这样 database/sql 就必定需要 import
![Screenshot_20231213_010850](https://github.com/SpectatorNan/gorm-zero/assets/105289582/06903d1d-ecee-468c-83a6-69861e56cd47)

**Comment by SpectatorNan** [comment]
import database/sql  报错有通过gorm-zero 支持的 goctl 修改版本 
生成代码的时候回去检查有没有可选参数 判断引用

**Comment by klen-ygs** [comment]
我看到了你发布的gorm-zero 支持的 goctl 修改版本, 我上面谈到的方案是使用**官方的goctl**也能生成正确代码
