### ISSUE TITLE
go-zero 1.4.0 模版替换

### ISSUE THREAD

**Issue by biancheng347** [SpectatorNan/gorm-zero#5]
go-zero 1.4.0 模版替换 我不知道怎么替换，能否有个教程，谢谢

**Comment by SpectatorNan** [comment]
本地生成模板文件之后 ，使用gorm-zero项目下的template/1.3.4下的model文件夹替换模板路径下的model文件夹即可

**Comment by SpectatorNan** [comment]
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/13959374/196328996-a83ec797-e6b6-42f3-955a-9197ee05aa27.png">

**Comment by biancheng347** [comment]
谢谢 ，嗯，  前提需要 gocel template init ,

**Comment by biancheng347** [comment]
还有 如果老项目中有 null  怎么处理，我看到了 model  sql.nullstring  sql.nullin64  这样的代码

**Comment by SpectatorNan** [comment]
> 谢谢 ，嗯， 前提需要 goctl template init ,

不一定要init  你如果只使用model模板的话  可以只弄一个 template/model 。 生成model的时候指向就可以了

**Comment by SpectatorNan** [comment]
> 还有 如果老项目中有 null 怎么处理，我看到了 model sql.nullstring sql.nullin64 这样的代码

go sql 中含有 sql.Nullxxx 
这个goctl内置生成了可空类型 具体用法可以点进去看下

gorm 也支持 *string or *int64

**Comment by biancheng347** [comment]
gorm 也支持 *string or *int64   怎么用？

**Comment by mqray** [comment]
我在项目底下使用 goctl template init --home ./template
cd template/model
然后将仓库里最新的 https://github.com/SpectatorNan/gorm-zero/tree/main/template/1.7.0/model 拷贝到 template中 然后运行 
goctl model pg datasource -url="postgres://root:ILt46dUAMEODK6hjIoxw@10.65.196.36:31827/platform_log?sslmode=disable" -table="t_opr_log" -dir="./model" -home ./template
最后 生成的model/toprlogmodel_gen.go 里默认实现的 属性是 conn  sqlx.SqlConn
		table string 这似乎是和预期不一致的吧?

**Comment by mqray** [comment]
是不支持pg么？

**Comment by SpectatorNan** [comment]
goctl model pg datasource -url="postgres://pguser:ppgguserss@localhost:5432/db_name?sslmode=disable" -table=${table}  -dir=${dir} -cache=true --style=goZero --home=template -useGorm=true  你需要开启缓存么 确认template指向路径正确么

> 我在项目底下使用 goctl template init --home ./template cd template/model 然后将仓库里最新的 https://github.com/SpectatorNan/gorm-zero/tree/main/template/1.7.0/model 拷贝到 template中 然后运行 goctl model pg datasource -url="postgres://root:ILt46dUAMEODK6hjIoxw@10.65.196.36:31827/platform_log?sslmode=disable" -table="t_opr_log" -dir="./model" -home ./template 最后 生成的model/toprlogmodel_gen.go 里默认实现的 属性是 conn sqlx.SqlConn table string 这似乎是和预期不一致的吧?
