### ISSUE TITLE
缺少database/sql的引用

### ISSUE THREAD

**Issue by xiongdashan** [SpectatorNan/gorm-zero#62]
你好：
当使用grom.Model时生成XXmodel_gen.go中的Struct 有 sql.NullTime 时，缺少对database/sql的引用 ，这个有什么解决方案。
谢谢

![image](https://github.com/SpectatorNan/gorm-zero/assets/23569431/3306e5c1-7bf3-4981-b0ac-596a06177f31)

**Comment by SpectatorNan** [comment]
有两种解决方案。
1. 使用gorm zero 适配版 goctl 生成代码 ，这里是仓库地址，可以自行编译goctl [代码地址](https://github.com/SpectatorNan/go-zero/tree/gorm-zero-support)
2. 使用这个方法 修改项目中FindOne的模板代码 添加 database/sql 的引用，并且使用下面的方法消除unused 警告
> https://github.com/SpectatorNan/gorm-zero/issues/45#issue-2038217667

**Comment by xiongdashan** [comment]
Tks
