### ISSUE TITLE
1.4.2的transaction是怎么使用的

### ISSUE THREAD

**Issue by yun36524** [SpectatorNan/gorm-zero#7]
你好，1.4.2的transaction是怎么使用的

**Comment by SpectatorNan** [comment]
已更新模板 增加了公开事务方法
``` golang
model.Transaction(l.ctx, func (conn *gorm.DB) error {
  err = model.Update(l.ctx, conn, user)
  if err != nil {
return err
}
return nil
})
```

**Comment by yun36524** [comment]
> 已更新模板 增加了公开事务方法
> 
> ```go
> model.Transaction(l.ctx, func (conn *gorm.DB) error {
>   err = model.Update(l.ctx, conn, user)
>   if err != nil {
> return err
> }
> return nil
> })
> ```

好的 谢谢
