### ISSUE TITLE
当created_at和updated_at,或者deleted_at，不叫这些的时候？不改模板能解决吗？还是说，可以从模板变量上解决呢？

### ISSUE THREAD

**Issue by yu1ec** [SpectatorNan/gorm-zero#76]
佬，我们公司的数据表，所有都是create_time,update_time,这时候，不会自动创建和更新时间，这时候我能想到的就是，改模板，还有什么别的方法吗？

**Comment by SpectatorNan** [comment]
咦，直接回邮件没有回复消息给你，我看下了下 如果有需要你可以直接改模板  hook更新你的关键字  并且去除 {{ if .gormCreatedAt }}   {{ if .gormUpdatedAt}}  这两个判断就好了。  目前官方原版的goctl也没有这两个关键字支持，我使用的是自己修改过后的goctl。 我看了下源码，写的时候因为这几个关键字是gorm官方默认 所以没有去添加自定义支持，魔改goctl目前基本就我自己使用，所以目前不会添加这块的支持

**Comment by yu1ec** [comment]
好的，好的，目前我也没想到好的方案，所以问问看你。

**Comment by yu1ec** [comment]
大佬，您看下，https://github.com/SpectatorNan/gorm-zero/pull/81 这个pr，这是简单的实现，我不确定，是不是要做成类似customCacheKeys这种形式，因为，俺寻思，这一个表，需要忽略的字段是固定的。

**Comment by SpectatorNan** [comment]
缓存建议全量缓存，你这个忽略字段操作如果是想在更新数据库的时候进行增量更新，推荐在BeforeUpdate中进行操作  
[gorm 检查字段是否更新](https://gorm.io/zh_CN/docs/update.html#%E6%A3%80%E6%9F%A5%E5%AD%97%E6%AE%B5%E6%98%AF%E5%90%A6%E6%9C%89%E5%8F%98%E6%9B%B4%EF%BC%9F)
