### ISSUE TITLE
1.4.2的版本 引入的依赖有些没用到

### ISSUE THREAD

**Issue by solitudealma** [SpectatorNan/gorm-zero#8]
对比了一下是因为vars修改了。应该同步改一下吧
比如strings这个包
还有database/sql需要加上_

**Comment by SpectatorNan** [comment]
感谢反馈  模板已更新
database/sql 需手动导入
使用_ 当含有 sql.NullXxx类型的时候还会引入一个 database/sql
所以我打包了一个支持gorm-zero模板的goctl 如果不想手动处理 可以在release page 下载对应的goctl
[release page](https://github.com/SpectatorNan/gorm-zero/releases/tag/v1.1.0)

**Comment by solitudealma** [comment]
好的好的，这个我倒是不太清楚

**Comment by SpectatorNan** [comment]
> 可以把goctl的那个sql.Nullxx弄掉吗 感觉挺烦的 或者说定义表的时候最好不为空 如果需要空值就给个类型的空值？像gozerolooklook的作者那样做

sql.NullXxx是 go的sql可空类型 
如果字段为非必填项  他就不会是sql.NullXxx

**Comment by solitudealma** [comment]
> 
这个我倒是清楚，就是它这个自动生成不像gorm那样就很烦
还有我想问个问题，你那个gormCreatedAt这个变量是自己定义的吗 自定义模板可以自己定义变量吗 我好像没看到，因为我想换个名字 如果不可以的话就换回来

**Comment by SpectatorNan** [comment]
> > 
> 
> 这个我倒是清楚，就是它这个自动生成不像gorm那样就很烦 还有我想问个问题，你那个gormCreatedAt这个变量是自己定义的吗 自定义模板可以自己定义变量吗 我好像没看到，因为我想换个名字 如果不可以的话就换回来

这个不支持自定义 官方goctl 也不支持这个变量
是通过修改 官方goctl 才支持的 采用的gorm默认的变量名

**Comment by solitudealma** [comment]
> > > 
> > 
> > 
> > 这个我倒是清楚，就是它这个自动生成不像gorm那样就很烦 还有我想问个问题，你那个gormCreatedAt这个变量是自己定义的吗 自定义模板可以自己定义变量吗 我好像没看到，因为我想换个名字 如果不可以的话就换回来
> 
> 这个不支持自定义 官方goctl 也不支持这个变量 是通过修改 官方goctl 才支持的 采用的gorm默认的变量名

嗯嗯

**Comment by solitudealma** [comment]
我刚刚试了一下生成rpc服务，然后logicName会有问题，源码上同样的logicName在不同的两个tpl表现是不一样的。具体就是
```go
//不是严格的驼峰
type SubmitcodeLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
	logx.Logger
}

func NewSubmitcodeLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SubmitcodeLogic {
	return &SubmitcodeLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
		Logger: logx.WithContext(ctx),
	}
}
// 正常
func (l *SubmitCodeLogic) SubmitCode(in *pb.RunCodeReq) (*pb.RunCodeResp, error) {
	// todo: add your logic here and delete this line

	return &pb.RunCodeResp{}, nil
}
```

我试过官方的goctl是正常的，可能是修改源码的时候把rpc的部分影响到了，有空可以看看。虽然用了makefile方便了点，但是需要改命令（怕改来改去自己找不到问题hh），现在暂时的解决方案是和官方的工具一起用，然后让gormc直接指定到具体目录下，而不是让它自己去找对应版本

**Comment by SpectatorNan** [comment]
> 我刚刚试了一下生成rpc服务，然后logicName会有问题，源码上同样的logicName在不同的两个tpl表现是不一样的。具体就是
> 
> ```
> //不是严格的驼峰
> type SubmitcodeLogic struct {
> 	ctx    context.Context
> 	svcCtx *svc.ServiceContext
> 	logx.Logger
> }
> 
> func NewSubmitcodeLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SubmitcodeLogic {
> 	return &SubmitcodeLogic{
> 		ctx:    ctx,
> 		svcCtx: svcCtx,
> 		Logger: logx.WithContext(ctx),
> 	}
> }
> // 正常
> func (l *SubmitCodeLogic) SubmitCode(in *pb.RunCodeReq) (*pb.RunCodeResp, error) {
> 	// todo: add your logic here and delete this line
> 
> 	return &pb.RunCodeResp{}, nil
> }
> ```
> 
> 我试过官方的goctl是正常的，可能是修改源码的时候把rpc的部分影响到了，有空可以看看。虽然用了makefile方便了点，但是需要改命令（怕改来改去自己找不到问题hh），现在暂时的解决方案是和官方的工具一起用，然后让gormc直接指定到具体目录下，而不是让它自己去找对应版本

最近小洋人 没有及时回复  这个问题之前有发现 官方master分支代码生成的 goctl 存在这个问题  还在讨论中
不过我在release里面打的那个包有修改 你是什么OS

**Comment by solitudealma** [comment]
> goctl

Linux，因为我要用makefile，在win上麻烦点，所以我是在wsl2的Ubuntu20.04写的代码

**Comment by solitudealma** [comment]
> > 我刚刚试了一下生成rpc服务，然后logicName会有问题，源码上同样的logicName在不同的两个tpl表现是不一样的。具体就是
> 
> > 
> 
> > ```
> 
> > //不是严格的驼峰
> 
> > type SubmitcodeLogic struct {
> 
> > 	ctx    context.Context
> 
> > 	svcCtx *svc.ServiceContext
> 
> > 	logx.Logger
> 
> > }
> 
> > 
> 
> > func NewSubmitcodeLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SubmitcodeLogic {
> 
> > 	return &SubmitcodeLogic{
> 
> > 		ctx:    ctx,
> 
> > 		svcCtx: svcCtx,
> 
> > 		Logger: logx.WithContext(ctx),
> 
> > 	}
> 
> > }
> 
> > // 正常
> 
> > func (l *SubmitCodeLogic) SubmitCode(in *pb.RunCodeReq) (*pb.RunCodeResp, error) {
> 
> > 	// todo: add your logic here and delete this line
> 
> > 
> 
> > 	return &pb.RunCodeResp{}, nil
> 
> > }
> 
> > ```
> 
> > 
> 
> > 我试过官方的goctl是正常的，可能是修改源码的时候把rpc的部分影响到了，有空可以看看。虽然用了makefile方便了点，但是需要改命令（怕改来改去自己找不到问题hh），现在暂时的解决方案是和官方的工具一起用，然后让gormc直接指定到具体目录下，而不是让它自己去找对应版本
> 
> 
> 
> 最近小洋人 没有及时回复  这个问题之前有发现 官方master分支代码生成的 goctl 存在这个问题  还在讨论中
> 
> 不过我在release里面打的那个包有修改 你是什么OS

Linux，因为我要用makefile，在win上麻烦点，所以我是在wsl2的Ubuntu20.04写的代码
但是我下载过官方的最新版好像没有这个问题

**Comment by SpectatorNan** [comment]
> > > 我刚刚试了一下生成rpc服务，然后logicName会有问题，源码上同样的logicName在不同的两个tpl表现是不一样的。具体就是
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > //不是严格的驼峰
> > 
> > 
> > > type SubmitcodeLogic struct {
> > 
> > 
> > > ```
> > > ctx    context.Context
> > > ```
> > 
> > 
> > > ```
> > > svcCtx *svc.ServiceContext
> > > ```
> > 
> > 
> > > ```
> > > logx.Logger
> > > ```
> > 
> > 
> > > }
> > 
> > 
> > > 
> > 
> > 
> > > func NewSubmitcodeLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SubmitcodeLogic {
> > 
> > 
> > > ```
> > > return &SubmitcodeLogic{
> > > ```
> > 
> > 
> > > ```
> > > 	ctx:    ctx,
> > > ```
> > 
> > 
> > > ```
> > > 	svcCtx: svcCtx,
> > > ```
> > 
> > 
> > > ```
> > > 	Logger: logx.WithContext(ctx),
> > > ```
> > 
> > 
> > > ```
> > > }
> > > ```
> > 
> > 
> > > }
> > 
> > 
> > > // 正常
> > 
> > 
> > > func (l *SubmitCodeLogic) SubmitCode(in *pb.RunCodeReq) (*pb.RunCodeResp, error) {
> > 
> > 
> > > ```
> > > // todo: add your logic here and delete this line
> > > ```
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > return &pb.RunCodeResp{}, nil
> > > ```
> > 
> > 
> > > }
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > 我试过官方的goctl是正常的，可能是修改源码的时候把rpc的部分影响到了，有空可以看看。虽然用了makefile方便了点，但是需要改命令（怕改来改去自己找不到问题hh），现在暂时的解决方案是和官方的工具一起用，然后让gormc直接指定到具体目录下，而不是让它自己去找对应版本
> > 
> > 
> > 最近小洋人 没有及时回复  这个问题之前有发现 官方master分支代码生成的 goctl 存在这个问题  还在讨论中
> > 不过我在release里面打的那个包有修改 你是什么OS
> 
> Linux，因为我要用makefile，在win上麻烦点，所以我是在wsl2的Ubuntu20.04写的代码 但是我下载过官方的最新版好像没有这个问题

release 页 更新的包 你可以去下载新的试试

**Comment by solitudealma** [comment]
> > > > 我刚刚试了一下生成rpc服务，然后logicName会有问题，源码上同样的logicName在不同的两个tpl表现是不一样的。具体就是
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > //不是严格的驼峰
> > > 
> > > 
> > > > type SubmitcodeLogic struct {
> > > 
> > > 
> > > > ```
> > > > ctx    context.Context
> > > > ```
> > > 
> > > 
> > > > ```
> > > > svcCtx *svc.ServiceContext
> > > > ```
> > > 
> > > 
> > > > ```
> > > > logx.Logger
> > > > ```
> > > 
> > > 
> > > > }
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > func NewSubmitcodeLogic(ctx context.Context, svcCtx *svc.ServiceContext) *SubmitcodeLogic {
> > > 
> > > 
> > > > ```
> > > > return &SubmitcodeLogic{
> > > > ```
> > > 
> > > 
> > > > ```
> > > > 	ctx:    ctx,
> > > > ```
> > > 
> > > 
> > > > ```
> > > > 	svcCtx: svcCtx,
> > > > ```
> > > 
> > > 
> > > > ```
> > > > 	Logger: logx.WithContext(ctx),
> > > > ```
> > > 
> > > 
> > > > ```
> > > > }
> > > > ```
> > > 
> > > 
> > > > }
> > > 
> > > 
> > > > // 正常
> > > 
> > > 
> > > > func (l *SubmitCodeLogic) SubmitCode(in *pb.RunCodeReq) (*pb.RunCodeResp, error) {
> > > 
> > > 
> > > > ```
> > > > // todo: add your logic here and delete this line
> > > > ```
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > ```
> > > > return &pb.RunCodeResp{}, nil
> > > > ```
> > > 
> > > 
> > > > }
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 我试过官方的goctl是正常的，可能是修改源码的时候把rpc的部分影响到了，有空可以看看。虽然用了makefile方便了点，但是需要改命令（怕改来改去自己找不到问题hh），现在暂时的解决方案是和官方的工具一起用，然后让gormc直接指定到具体目录下，而不是让它自己去找对应版本
> > > 
> > > 
> > > 最近小洋人 没有及时回复  这个问题之前有发现 官方master分支代码生成的 goctl 存在这个问题  还在讨论中
> > > 不过我在release里面打的那个包有修改 你是什么OS
> > 
> > 
> > Linux，因为我要用makefile，在win上麻烦点，所以我是在wsl2的Ubuntu20.04写的代码 但是我下载过官方的最新版好像没有这个问题
> 
> release 页 更新的包 你可以去下载新的试试

ok,有空我试试
