### ISSUE TITLE
如何支持mysql的json类型

### ISSUE THREAD

**Issue by xiongdashan** [SpectatorNan/gorm-zero#87]
HI：

数据库字段 ： 

```
`field_name` json DEFAULT NULL,

```

期望生成的类型为：

```
FieldName   datatypes.JSON `gorm:"column:field_name"`
```
实际生成类型：

```
FieldName   sql.NullString `gorm:"column:field_name"`

```

请问如何实现，感谢！

**Comment by SpectatorNan** [comment]
datatypes 是gorm 提供的json类型库，goctl不是提供支持的，如果想要实现这种需要自己去修改goctl代码。
datatypes.JSON 为 []byte类型， 
另推荐：
结构类型推荐使用 datatypes.JSONType
slices类型推荐使用 datatypes.JSONSlice

我目前的使用方式使用组合的方式使用， 在Model中声明一个查询的类型，避免gen中覆盖
![image](https://github.com/user-attachments/assets/8394d7da-7616-4dc0-ae64-fdc1796296f3)

**Comment by xiongdashan** [comment]
感谢回复和建议。
你说的

> 使用方式使用组合的方式使用， 在Model中声明一个查询的类型，避免gen中覆盖

没太明白，是否可以详细些。tks

**Comment by SpectatorNan** [comment]
goctls生成的model会有两个文件 tableModel 和 tableModel_gen。 _gen 文件是每次生成都会覆盖的文件。所以手动声明的建议在tableModel文件中声明。 因为通过go的组合特性 覆盖 如以上回复中的Content字段

**Comment by xiongdashan** [comment]
明白了，感谢！
