### ISSUE TITLE
 请问template的1.7.0是否还不可用？

### ISSUE THREAD

**Issue by space-water-bear** [SpectatorNan/gorm-zero#93]
go.mod => github.com/SpectatorNan/gorm-zero v1.5.0
goctl => 1.7.0
template =>  1.7.0

使用了goctl model 生成了以下内容
```
func (m *defaultGameServiceModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []GameService) error {

	err := m.ExecNoCacheCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		} 
		return db.Create(&news).Error
	})
	return err
}
```
其中ExecNoCacheCtx没有找到该方法

如果是我的操作有问题请指出来，谢谢🙏

**Comment by SpectatorNan** [comment]
不带缓存的模板有问题 稍等更新

**Comment by SpectatorNan** [comment]
> go.mod => github.com/SpectatorNan/gorm-zero v1.5.0 goctl => 1.7.0 template => 1.7.0
> 
> 使用了goctl model 生成了以下内容
> 
> ```
> func (m *defaultGameServiceModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []GameService) error {
> 
> 	err := m.ExecNoCacheCtx(ctx, func(conn *gorm.DB) error {
> 		db := conn
> 		if tx != nil {
> 			db = tx
> 		} 
> 		return db.Create(&news).Error
> 	})
> 	return err
> }
> ```
> 
> 其中ExecNoCacheCtx没有找到该方法
> 
> 如果是我的操作有问题请指出来，谢谢🙏

新模板文件已更新

**Comment by space-water-bear** [comment]
ok，这个问题解决了，但是又发现新的问题，当字段允许为空时，没有import "database/sql"

**Comment by SpectatorNan** [comment]
两种解决方案：
1.
[release 页面有提供gorm专用版本goctl仓库地址](https://github.com/SpectatorNan/gorm-zero/releases/tag/v1.1.2)
提供了一个useGorm参数会去检查是否需要引入database/sql

goctl model pg datasource -url="postgres://xxx:xxx@localhost:5432/xxx?sslmode=disable" -table=${table}  -dir=${dir} -cache=true --style=goZero --home=template -useGorm=true

2.
也可以自行修改模板在任意一个语句中使用nameArg[docs](https://gorm.io/docs/advanced_query.html#Named-Argument)
确保database/sql百分百被使用
![image](https://github.com/user-attachments/assets/95b79c9a-7504-48af-af8d-e8212d17db00)
移除import中的判断条件
